spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

cards:
  message: "Welcome to CapgeBank cards related QA APIs"
  contactDetails:
    name: "Jack Smith - QA Lead"
    email: "jack@gmail.com"
  onCallSupport:
    - (222) 364-7374
    - (333) 938-9273