spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    #url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5435}/${DATABASE_HOST:loansdb}
    url: jdbc:postgresql://${DATABASE_HOST:host.docker.internal}:${DATABASE_PORT:5435}/${DATABASE_HOST:loansdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Capge7878}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.properties.hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090