spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to CapgeBank loans related PROD APIs"
  contactDetails:
    name: "Ryan Sin - Product Owner"
    email: "ryan@gmail.com"
  onCallSupport:
    - (111) 777-2938
    - (555) 646-2884