spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5435}/${DATABASE_HOST:loansdb}
    #url: jdbc:postgresql://${DATABASE_HOST:host.docker.internal}:${DATABASE_PORT:5435}/${DATABASE_HOST:loansdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Capge7878}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.properties.hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Capge Bank Loans Application"
    version: "1.0.0"

server:
  port: 8090

logging:
  level:
    com:
      capgebank:
        loans: DEBUG