spring:
  datasource:
    #url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_HOST:springboot_micro_kube}
    url: jdbc:postgresql://${DATABASE_HOST:host.docker.internal}:${DATABASE_PORT:5432}/${DATABASE_HOST:springboot_micro_kube}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Capge7878}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.properties.hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"
server:
  port: 8090

build:
  version: "3.0"

loans:
  message: "Welcome to CapgeBank loans related local APIs"
  contactDetails:
    name: "Sudhakar - Developer"
    email: "sudhakar@gmail.com"
  onCallSupport:
    - (444) 555-1234
    - (555) 333-7384