server:
  port: 9000

build:
  version: "3.0"

cards:
  message: "Welcome to CapgeBank cards related local APIs"
  contactDetails:
    name: "Sudhakar - Developer"
    email: "sudhakar@gmail.com"
  onCallSupport:
    - (444) 555-1234
    - (555) 333-7384